### ISSUE TITLE
commit counts are inconsistent

### ISSUE THREAD

**Issue by whilei** [ethereumproject/janus#4]
AppVeyor and Travis can sometimes yield different commit counts since last tag. This has caused issues both with Janus and with Bintray deploys.

I think this is related:
```
The number of commits alone can't tell you anything if there are any merges in your history.
[...]
but if you have even a single active side branch at the time of your tag then this may not work.

If you need reliable release numbers, you should stick to explicit tags.
```
> https://stackoverflow.com/questions/8595391/how-to-show-git-commit-using-number-of-commits-since-a-tag

**Comment by splix** [comment]
Yeah, I thought about it, that's a problem
