### ISSUE TITLE
Use GPG (instead of OpenSSL)

### ISSUE THREAD

**Issue by tzdybal** [ethereumproject/janus#8]
OpenSSL symmetric encryption is not portable and not very secure:
 - key derivation function changes from version to version, and it's not a standard, well known function, considered as secure,
 - encrypted file does not store any information about the OpenSSL version, used cipher, etc
 - in older versions MD5 is used during encryption process
 - some encryption options are not documented
 - **file encrypted with one version of OpenSSL may not be usable with different version of OpenSSL** (even with correct password, same cipher, etc)
 - default version available in MacOS is pre-historical, and installing new version is "not so easy" (`brew update openssl` is not enough (and the *new* version is quite old anyways))

On the other hand, file encrypted with GPG:
 - contains information about used cipher algorithm -> **it is portable**
 - use standard & secure key derivation function,
 - in general, encryption is cryptographically stronger/safer
 
Some reference: https://stackoverflow.com/questions/28247821/openssl-vs-gpg-for-encrypting-off-site-backups

Because GPG is more portable and safer than OpenSSL, I think that GPG should:
 - replace OpenSSL, or
 - be added as another option for encryption/decryption (to keep backward compatibility)

**Comment by tzdybal** [comment]
I had an issue on CircleCI - my "personal" OpenSSL is `1.1.0g`, while default in MacOS is `0.9.8zh` and can be updated to `1.0.2n`. File encrypted with my version cannot be decrypted with the older version.

**Comment by splix** [comment]
One thing to add, for symmetric encryption the key size is much smaller, which could be considered as a plus. On other hand, for pgp anyone can put, say GCP keys, by using only public key, that could be useful too

**Comment by tzdybal** [comment]
For clarification: I meant using AES-256, but from GPG instead of openssl, like:
- `gpg --symmetric --cipher-algo AES256 filename` for encryption,
- `gpg --decrypt filename.gpg` for decryption.

**Comment by splix** [comment]
Ah, got it
